// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6znT4zOuAcWN7R70PlKnEjymLcVxRA0c',
    appId: '1:899409460852:web:1ac4777a3029439b109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    authDomain: 'testapp-fb888.firebaseapp.com',
    storageBucket: 'testapp-fb888.appspot.com',
    measurementId: 'G-0R5EVXPY04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeV56StBEmEwSo55y9szjvH3-oPjTZbc0',
    appId: '1:899409460852:android:ad5c9491cbec1ec9109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    storageBucket: 'testapp-fb888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruEtE0fYeqiRsTglcIaNKUXnoVn6JhgQ',
    appId: '1:899409460852:ios:fcdbe6e7760e0db3109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    storageBucket: 'testapp-fb888.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCruEtE0fYeqiRsTglcIaNKUXnoVn6JhgQ',
    appId: '1:899409460852:ios:8bc007348b1da97e109b21',
    messagingSenderId: '899409460852',
    projectId: 'testapp-fb888',
    storageBucket: 'testapp-fb888.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
